name: boxzpot
description: Mapeador de Depósito Físico para o AtoM
publish_to: 'none'
version: 1.0.0-0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqlite3: ^2.4.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.24

flutter:
  uses-material-design: true
